# Exercise no. 2
---

<b id="Top"> </b>  


1. [Pandas](#section1)
2. [Numpy](#section2)
3. [Random](#section3)
4. [conditional selection](#section4)

---

<a id='section1'></a>

<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/Reading-and-Writing-Data-With-Pandas_Watermarked.png?raw=true" width="70%" height="20%" alt="Centered Image" /> <div  </h1>

<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/iloc_working.png?raw=true" width="40%" height="20%" alt="Centered Image" /> <div  </h1>


<a id='section1'></a>

In [2]:
import pandas as pd

# Create some variables
trials = range(1, 21)
n_rows = len(trials)
subj_id = [1]*n_rows
group = ['Control']*n_rows
condition = ['Affect']*int((n_rows/2)) + ['Neutral']*int((n_rows/2))

# Create a dictionairy
data = {'Condition':condition, 'Subject_ID':subj_id, 
        'Trial':trials, 'Group':group}

# Create the dataframe
df = pd.DataFrame(data)
df.head(10)

Condition  Subject_ID  Trial    Group
0    Affect           1      1  Control
1    Affect           1      2  Control
2    Affect           1      3  Control
3    Affect           1      4  Control
4    Affect           1      5  Control
5    Affect           1      6  Control
6    Affect           1      7  Control
7    Affect           1      8  Control
8    Affect           1      9  Control
9    Affect           1     10  Control

#### 1. Select row five to 10 __without__ using loc / iloc


#### 2. Select row five to 10 by using loc 

#### 3. Show only the value from row number 0 under the "Conditions" column

#### 4.1  print only the "Conditions" column , show all rows

#### 4.2  print only the "Conditions" and 'Group' column , show all rows

#### 5. Combine your answer from question 2 and question 4.2

#### 6. According to the slice you made in question 2: display the columns starting from the  'Subject_ID' column and forward and display again starting from 'Trial' column and forward

#### 7.1 Display the same dataframe as you did in question #1 by using __iloc__

#### 7.2 Now show only the first column

#### Display the first and last column by using __iloc__ , show all rows

#### Show all columns except the first column

#### According to the following line of code - what do you think will be displayed in the output?

### [▲](#Top)
---

<a id='section2'></a>

<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/Title_numpy.png?raw=true" width="50%" height="20%" alt="Centered Image" /> <div  </h1>

<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/Uses-of-NumPy-1.png?raw=true" width="80%" height="40%" alt="Centered Image" /> <div  </h1>



<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/nice_explain.png?raw=true" width="80%" height="40%" alt="Centered Image" /> <div  </h1>

---

### Numpy in terms of complexity



In [10]:
import numpy as np
import pandas as pd 

In [3]:
%%time 
my_list = list(range(10000000))
mult_by_3 = [3 * num for num in my_list]

CPU times: total: 828 ms
Wall time: 1.06 s


In [4]:
%%time 
my_array = np.arange(10000000)
mult_by_3 = 3 * my_array


CPU times: total: 0 ns
Wall time: 33.6 ms


In [7]:
1.06 / 33.6 * 0.001 

3.154761904761905e-05

### 3x faster using numpy
---

### [▲](#Top)
---

<a id='section3'></a>

## <b id="section_2">Some  </b> <b style='color:#F05454'>Random </b> <b>before Numpy.</b> 

In [13]:
import random # import library

In [15]:
# Method 1- using random method
num = random.random()
print(num)
# Result will always between (0,1)

0.6283311115999547


In [29]:
# Method 2- using randint method ---> Rand - int ---
num = random.randint(10, 20)
print(num)

10


In [ ]:
#Try to compute 
num = random.randint(10.5, 10.6) 
# Why is that ?

In [21]:
# Method 3- using randrange method

num = random.randrange(100,200,2) # (Start,Stop,Step)
print(num)

152


In [25]:
# Method 4- using uniform method

num = random.uniform(50,70) # (a,b)  
print(num)

# The uniform() method returns a random floating number between the two specified numbers
# (both included).

65.83690809920176


In [26]:
# Method 5- using sample method

numList = random.sample(range(150,250), 15)
print(numList)



[202, 224, 157, 234, 172, 175, 188, 242, 201, 205, 150, 228, 162, 193, 216]


In [27]:
# Method 6- using shuffle and choice method

numList = [1,2,3,4,5]
random.shuffle(numList)
print(numList)
print(random.choice(numList))

[2, 3, 5, 1, 4]
2


In [ ]:
# Method 7 - using random.choices is the same as #6 , try yourself !
# random.choices()

In [57]:
# Nice greeting

greetings = ['Hello', 'Hi', 'Hey', 'Howdy', 'Hola']
value = random.choice(greetings)
my_name = 'Your_Name'
print(value + ', ' + my_name)

Hola, Your_Name


### Exercise
#### Write a coin flip code, with 10 samples

In [6]:
coin = ['Tail', 'Head']
# המשיכו את הקוד כאן


#### Write code to flip an unfair coin so that the chance of getting a head is 90 percent

In [7]:
coin = ['Tail', 'Head']
# המשיכו את הקוד כאן


## <b id="section_2">Back to  </b> <b style='color:#F05454'>Numpy. </b> 

In [83]:
arr = np.array([1, 2, 3, 4, 5])
# . product
print(arr*arr)

[ 1  4  9 16 25]


#### vector multiplication

In [15]:

arr.dot(arr)
# or by
arr@arr


55

* create ones matrix of specific size:

In [16]:

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

* self excercise: Suggest how to create zeros matrix of specific size:

In [17]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

* Create any constant array

In [18]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [19]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


* self excercise: suggest how to create a 3X3 matrix where digonal has value of 8

#### self learning:
1. Read Lec3
2. Read the tutorials in links
3. Write a NumPy program to test whether none of the elements of a given array is zero (create a sample array).

### Result



import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

### 

### [▲](#Top)

---
<a id='section4'></a>
<h1 style="background-color: #fff4d9; color: #0046d6; border-radius: 20px; text-align: center; padding-top: 20px; padding-bottom: 20px; font-family: 'Arial'" id="introduction">conditional selection </h1>



#### Summary of the functions in unit 2:


>* `.index.values` - the row indexes of this part of the dataframes
>* `.str.contains` - selects rows and columns that contain a string
>* `.max` - maximum value
>* `.mean` - average value
>* `.count` - the number of rows that contain a value
>* `len()` - dataframe length

In [110]:
url = 'https://raw.githubusercontent.com/Razelbaz1/exercises-package/master/data/titanic.csv'
titanic_df = pd.read_csv(url)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3767: invalid continuation byte

In [3]:
titanic_df = pd.read_csv('titanic.csv',encoding='latin1')
titanic_df

row.names pclass  survived  \
0             1    1st         1   
1             2    1st         0   
2             3    1st         0   
3             4    1st         0   
4             5    1st         1   
...         ...    ...       ...   
1308       1309    3rd         0   
1309       1310    3rd         0   
1310       1311    3rd         0   
1311       1312    3rd         0   
1312       1313    3rd         0   

                                                 name      age     embarked  \
0                        Allen, Miss Elisabeth Walton  29.0000  Southampton   
1                         Allison, Miss Helen Loraine   2.0000  Southampton   
2                 Allison, Mr Hudson Joshua Creighton  30.0000  Southampton   
3     Allison, Mrs Hudson J.C. (Bessie Waldo Daniels)  25.0000  Southampton   
4                       Allison, Master Hudson Trevor   0.9167  Southampton   
...                                               ...      ...          ...   
1308                               Zakarian, Mr Artun      NaN          NaN   
1309                           Zakarian, Mr Maprieder      NaN          NaN   
1310                                  Zenn, Mr Philip      NaN          NaN   
1311                                    Zievens, Rene      NaN          NaN   
1312                                   Zimmerman, Leo      NaN          NaN   

                            home.dest room      ticket  boat     sex  
0                        St Louis, MO  B-5  24160 L221     2  female  
1     Montreal, PQ / Chesterville, ON  C26         NaN   NaN  female  
2     Montreal, PQ / Chesterville, ON  C26         NaN  -135    male  
3     Montreal, PQ / Chesterville, ON  C26         NaN   NaN  female  
4     Montreal, PQ / Chesterville, ON  C22         NaN    11    male  
...                               ...  ...         ...   ...     ...  
1308                              NaN  NaN         NaN   NaN    male  
1309                              NaN  NaN         NaN   NaN    male  
1310                              NaN  NaN         NaN   NaN    male  
1311                              NaN  NaN         NaN   NaN  female  
1312                              NaN  NaN         NaN   NaN    male  

[1313 rows x 11 columns]

In [135]:
titanic_df.columns

Index(['row.names', 'pclass', 'survived', 'name', 'age', 'embarked',
       'home.dest', 'room', 'ticket', 'boat', 'sex'],
      dtype='object')

#### 1. Display a table so that you see all the passengers who belong to the third class
##### For your convenience, the list of columns is given

#### 2. Display a table so that you see all the passengers belonging to the third <ins>**or**</ins> second class

#### Suggest a solution in another way

In [118]:
len(titanic_df)

1313

#### 3. Display the oldest age on the ship, display only one row of that age

#### 4. Display the youngest age on the ship, display only one row of that age

#### 5. Are there more men than women on the ship? Show the solution by a function learned in class
#### Show in 2 different ways

#### 6. Note that there is a column that shows who survived the disaster, which gender survived more?

#### 7. Find the passenger who goes by the name 'Maprieder', did he survive?

#### 8. Is there only one such name ?