# Exercise no. 2
---

<b id="Top"> </b>  

1. [Pandas](#section1)
2. [Numpy](#section2)
3. [Random](#section3)
4. [conditional selection](#section4)
---

<a id='section1'></a>

<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/Reading-and-Writing-Data-With-Pandas_Watermarked.png?raw=true" width="70%" height="20%" alt="Centered Image" /> <div  </h1>

<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/iloc_working.png?raw=true" width="40%" height="20%" alt="Centered Image" /> <div  </h1>


In [1]:
import pandas as pd
import numpy as np

# Create some variables
trials = range(1, 21)
n_rows = len(trials)
subj_id = list(range(1, n_rows + 1))
group_options = ['Control', 'Experimental1', 'Experimental2']  
condition = ['Affect'] * int((n_rows/2)) + ['Neutral'] * int((n_rows/2))

# Create a dictionary
data = {'Condition': condition, 'Subject_ID': subj_id, 'Trial': trials}

# Add random 'Group' values from the available options
data['Group'] = np.random.choice(group_options, n_rows)

# Create the dataframe
df = pd.DataFrame(data)
df.head(10)


Condition  Subject_ID  Trial          Group
0    Affect           1      1        Control
1    Affect           2      2  Experimental2
2    Affect           3      3        Control
3    Affect           4      4        Control
4    Affect           5      5  Experimental1
5    Affect           6      6  Experimental2
6    Affect           7      7  Experimental1
7    Affect           8      8        Control
8    Affect           9      9        Control
9    Affect          10     10        Control

In [1]:
import pandas as pd

# Create some variables
trials = range(1, 21)
n_rows = len(trials)
subj_id = [1]*n_rows
group = ['Control']*n_rows
condition = ['Affect']*int((n_rows/2)) + ['Neutral']*int((n_rows/2))

# Create a dictionary
data = {'Condition':condition, 'Subject_ID':subj_id, 
        'Trial':trials, 'Group':group}

# Create the dataframe
df = pd.DataFrame(data)
df.head(10)

Condition  Subject_ID  Trial    Group
0    Affect           1      1  Control
1    Affect           1      2  Control
2    Affect           1      3  Control
3    Affect           1      4  Control
4    Affect           1      5  Control
5    Affect           1      6  Control
6    Affect           1      7  Control
7    Affect           1      8  Control
8    Affect           1      9  Control
9    Affect           1     10  Control

#### 1. Select row five to 10 __without__ using loc / iloc


In [10]:
# Select row five to 10 
df[4:10:1]

Condition  Subject_ID  Trial    Group
4    Affect           1      5  Control
5    Affect           1      6  Control
6    Affect           1      7  Control
7    Affect           1      8  Control
8    Affect           1      9  Control
9    Affect           1     10  Control

#### 2. Select row five to 10 by using loc 

In [94]:
df.loc[4:9,:]

Condition  Subject_ID  Trial    Group
4    Affect           1      5  Control
5    Affect           1      6  Control
6    Affect           1      7  Control
7    Affect           1      8  Control
8    Affect           1      9  Control
9    Affect           1     10  Control

#### 3. Show only the value from row number 0 under the "Conditions" column

In [95]:
df.loc[0, 'Condition']

'Affect'

#### 4.1  print only the "Conditions" column , show all rows

In [96]:
# Printing out one column
df.loc[:, 'Condition']

0      Affect
1      Affect
2      Affect
3      Affect
4      Affect
5      Affect
6      Affect
7      Affect
8      Affect
9      Affect
10    Neutral
11    Neutral
12    Neutral
13    Neutral
14    Neutral
15    Neutral
16    Neutral
17    Neutral
18    Neutral
19    Neutral
Name: Condition, dtype: object

#### 4.2  print only the "Conditions" and 'Group' column , show all rows

In [97]:
# Printing out two columns
df.loc[:, ['Condition', 'Group']]

Condition    Group
0     Affect  Control
1     Affect  Control
2     Affect  Control
3     Affect  Control
4     Affect  Control
5     Affect  Control
6     Affect  Control
7     Affect  Control
8     Affect  Control
9     Affect  Control
10   Neutral  Control
11   Neutral  Control
12   Neutral  Control
13   Neutral  Control
14   Neutral  Control
15   Neutral  Control
16   Neutral  Control
17   Neutral  Control
18   Neutral  Control
19   Neutral  Control

#### 5. Combine your answer from question 2 and question 4.2

In [98]:
# Printing out from second column
df.loc[4:9, ['Condition', 'Group']]

Condition    Group
4    Affect  Control
5    Affect  Control
6    Affect  Control
7    Affect  Control
8    Affect  Control
9    Affect  Control

#### 6. According to the slice you made in question 2: display the columns starting from the  'Subject_ID' column and forward and display again starting from 'Trial' column and forward

In [99]:
# From column 'Subject_ID' and forward
df.loc[4:9, 'Subject_ID':]

# From column 'Trial' and forward
# df.loc[4:9, 'Trial':]

Subject_ID  Trial    Group
4           1      5  Control
5           1      6  Control
6           1      7  Control
7           1      8  Control
8           1      9  Control
9           1     10  Control

#### 7.1 Display the same dataframe as you did in question #1 by using __iloc__

In [100]:
# Printing out fifth to the twentieth row and all columns
# Note the difference!
df.iloc[4:10,:]

Condition  Subject_ID  Trial    Group
4    Affect           1      5  Control
5    Affect           1      6  Control
6    Affect           1      7  Control
7    Affect           1      8  Control
8    Affect           1      9  Control
9    Affect           1     10  Control

#### 7.2 Now show only the first column

In [101]:
df.iloc[4:10, 0]

4    Affect
5    Affect
6    Affect
7    Affect
8    Affect
9    Affect
Name: Condition, dtype: object

#### Display the first and last column by using __iloc__ , show all rows

In [102]:
df.iloc[4:10, [0, 3]]

Condition    Group
4    Affect  Control
5    Affect  Control
6    Affect  Control
7    Affect  Control
8    Affect  Control
9    Affect  Control

#### Show all columns except the first column

In [103]:
df.iloc[4:10, 1:]

Subject_ID  Trial    Group
4           1      5  Control
5           1      6  Control
6           1      7  Control
7           1      8  Control
8           1      9  Control
9           1     10  Control

#### According to the following line of code - what do you think will be displayed in the output?

### [▲](#Top)
---

<a id='section2'></a>

<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/Title_numpy.png?raw=true" width="50%" height="20%" alt="Centered Image" /> <div  </h1>

<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/Uses-of-NumPy-1.png?raw=true" width="80%" height="40%" alt="Centered Image" /> <div  </h1>



<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/nice_explain.png?raw=true" width="80%" height="40%" alt="Centered Image" /> <div  </h1>

---

### Numpy in terms of complexity



In [10]:
import numpy as np
import pandas as pd 

In [3]:
%%time 
my_list = list(range(10000000))
mult_by_3 = [3 * num for num in my_list]

CPU times: total: 828 ms
Wall time: 1.06 s


In [4]:
%%time 
my_array = np.arange(10000000)
mult_by_3 = 3 * my_array


CPU times: total: 0 ns
Wall time: 33.6 ms


In [7]:
1.06 / 33.6 * 0.001 

3.154761904761905e-05

### 3x faster using numpy
---

### [▲](#Top)
---

<a id='section3'></a>

## <b id="section_2">Some  </b> <b style='color:#F05454'>Random </b> <b>before Numpy.</b> 

In [13]:
import random # import library

In [15]:
# Method 1- using random method
num = random.random()
print(num)
# Result will always between (0,1)

0.6283311115999547


In [29]:
# Method 2- using randint method ---> Rand - int ---
num = random.randint(10, 20)
print(num)

10


In [ ]:
#Try to compute 
num = random.randint(10.5, 10.6) 
# Why is that ?

In [21]:
# Method 3- using randrange method

num = random.randrange(100,200,2) # (Start,Stop,Step)
print(num)

152


In [25]:
# Method 4- using uniform method

num = random.uniform(50,70) # (a,b)  
print(num)

# The uniform() method returns a random floating number between the two specified numbers
# (both included).

65.83690809920176


In [26]:
# Method 5- using sample method

numList = random.sample(range(150,250), 15)
print(numList)



[202, 224, 157, 234, 172, 175, 188, 242, 201, 205, 150, 228, 162, 193, 216]


In [27]:
# Method 6- using shuffle and choice method

numList = [1,2,3,4,5]
random.shuffle(numList)
print(numList)
print(random.choice(numList))

[2, 3, 5, 1, 4]
2


In [ ]:
# Method 7 - using random.choices is the same as #6 , try yourself !
# random.choices()

In [57]:
# Nice greeting

greetings = ['Hello', 'Hi', 'Hey', 'Howdy', 'Hola']
value = random.choice(greetings)
my_name = 'Your_Name'
print(value + ', ' + my_name)

Hola, Your_Name


### Exercise
#### Write a coin flip code, with 10 samples

In [74]:
coin = ['Tail', 'Head']
value = random.choices(coin, k =10)
print(value)

['Head', 'Head', 'Head', 'Tail', 'Head', 'Head', 'Head', 'Tail', 'Tail', 'Tail']


#### Write code to flip an unfair coin so that the chance of getting a head is 90 percent

In [82]:
coin = ['Tail', 'Head']
value = random.choices(coin, weights= [1,9], k = 10)
print(value)

['Tail', 'Head', 'Head', 'Head', 'Head', 'Head', 'Head', 'Head', 'Head', 'Head']


## <b id="section_2">Back to  </b> <b style='color:#F05454'>Numpy. </b> 

In [83]:
arr = np.array([1, 2, 3, 4, 5])
# . product
print(arr*arr)

[ 1  4  9 16 25]


#### vector multiplication

In [15]:

arr.dot(arr)
# or by
arr@arr


55

* create ones matrix of specific size:

In [16]:

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

* self excercise: Suggest how to create zeros matrix of specific size:

In [17]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

* Create any constant array

In [18]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [19]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


* self excercise: suggest how to create a 3X3 matrix where digonal has value of 8

In [20]:
8*np.eye(3)

array([[8., 0., 0.],
       [0., 8., 0.],
       [0., 0., 8.]])

In [21]:
e = np.random.random((2,4))
print(e)

[[0.96996099 0.0216012  0.45281868 0.86035786]
 [0.71289388 0.81701331 0.4976724  0.21628525]]


#### self learning:
1. Read Lec3
2. Read the tutorials in links
3. Write a NumPy program to test whether none of the elements of a given array is zero (create a sample array).

In [22]:



import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


### [▲](#Top)

---
<a id='section4'></a>
<h1 style="background-color: #fff4d9; color: #0046d6; border-radius: 20px; text-align: center; padding-top: 20px; padding-bottom: 20px; font-family: 'Arial'" id="introduction">conditional selection </h1>



#### Summary of the functions in unit 2:


>* `.index.values` - the row indexes of this part of the dataframes
>* `.str.contains` - selects rows and columns that contain a string
>* `.max` - maximum value
>* `.mean` - average value
>* `.count` - the number of rows that contain a value
>* `len()` - dataframe length

In [110]:
url = 'https://raw.githubusercontent.com/Razelbaz1/exercises-package/master/data/titanic.csv'
titanic_df = pd.read_csv(url)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3767: invalid continuation byte

In [134]:
titanic_df = pd.read_csv('titanic.csv',encoding='latin1')
titanic_df

row.names pclass  survived  \
0             1    1st         1   
1             2    1st         0   
2             3    1st         0   
3             4    1st         0   
4             5    1st         1   
...         ...    ...       ...   
1308       1309    3rd         0   
1309       1310    3rd         0   
1310       1311    3rd         0   
1311       1312    3rd         0   
1312       1313    3rd         0   

                                                 name      age     embarked  \
0                        Allen, Miss Elisabeth Walton  29.0000  Southampton   
1                         Allison, Miss Helen Loraine   2.0000  Southampton   
2                 Allison, Mr Hudson Joshua Creighton  30.0000  Southampton   
3     Allison, Mrs Hudson J.C. (Bessie Waldo Daniels)  25.0000  Southampton   
4                       Allison, Master Hudson Trevor   0.9167  Southampton   
...                                               ...      ...          ...   
1308                               Zakarian, Mr Artun      NaN          NaN   
1309                           Zakarian, Mr Maprieder      NaN          NaN   
1310                                  Zenn, Mr Philip      NaN          NaN   
1311                                    Zievens, Rene      NaN          NaN   
1312                                   Zimmerman, Leo      NaN          NaN   

                            home.dest room      ticket  boat     sex  
0                        St Louis, MO  B-5  24160 L221     2  female  
1     Montreal, PQ / Chesterville, ON  C26         NaN   NaN  female  
2     Montreal, PQ / Chesterville, ON  C26         NaN  -135    male  
3     Montreal, PQ / Chesterville, ON  C26         NaN   NaN  female  
4     Montreal, PQ / Chesterville, ON  C22         NaN    11    male  
...                               ...  ...         ...   ...     ...  
1308                              NaN  NaN         NaN   NaN    male  
1309                              NaN  NaN         NaN   NaN    male  
1310                              NaN  NaN         NaN   NaN    male  
1311                              NaN  NaN         NaN   NaN  female  
1312                              NaN  NaN         NaN   NaN    male  

[1313 rows x 11 columns]

In [135]:
titanic_df.columns

Index(['row.names', 'pclass', 'survived', 'name', 'age', 'embarked',
       'home.dest', 'room', 'ticket', 'boat', 'sex'],
      dtype='object')

#### 1. Display a table so that you see all the passengers who belong to the third class
##### For your convenience, the list of columns is given

In [136]:
titanic_df[titanic_df.loc[:,'pclass'] == '3rd' ].head()

row.names pclass  survived                          name   age  \
602        603    3rd         0            Abbing, Mr Anthony  42.0   
603        604    3rd         0  Abbott, Master Eugene Joseph  13.0   
604        605    3rd         0    Abbott, Mr Rossmore Edward  16.0   
605        606    3rd         1    Abbott, Mrs Stanton (Rosa)  35.0   
606        607    3rd         1     Abelseth, Miss Anna Karen  16.0   

        embarked               home.dest room ticket  boat     sex  
602  Southampton                     NaN  NaN    NaN   NaN    male  
603  Southampton     East Providence, RI  NaN    NaN   NaN    male  
604  Southampton     East Providence, RI  NaN    NaN  -190    male  
605  Southampton     East Providence, RI  NaN    NaN     A  female  
606  Southampton  Norway Los Angeles, CA  NaN    NaN    16  female

#### 2. Display a table so that you see all the passengers belonging to the third <ins>**or**</ins> second class

In [137]:
titanic_df_two_classes = titanic_df[(titanic_df.pclass == '3rd') | (titanic_df.pclass == '2nd')]
titanic_df_two_classes

row.names pclass  survived                        name   age  \
322         323    2nd         0          Abelson, Mr Samuel  30.0   
323         324    2nd         1  Abelson, Mrs Samuel (Anna)  28.0   
324         325    2nd         0     Andrew, Mr Edgar Samuel  18.0   
325         326    2nd         0            Andrew, Mr Frank   NaN   
326         327    2nd         0        Angle, Mr William A.  34.0   
...         ...    ...       ...                         ...   ...   
1308       1309    3rd         0          Zakarian, Mr Artun   NaN   
1309       1310    3rd         0      Zakarian, Mr Maprieder   NaN   
1310       1311    3rd         0             Zenn, Mr Philip   NaN   
1311       1312    3rd         0               Zievens, Rene   NaN   
1312       1313    3rd         0              Zimmerman, Leo   NaN   

         embarked                                 home.dest room ticket boat  \
322     Cherbourg                       Russia New York, NY  NaN    NaN  NaN   
323     Cherbourg                       Russia New York, NY  NaN    NaN   12   
324   Southampton  Buenos Aires, Argentina / New Jersey, NJ  NaN    NaN  NaN   
325   Southampton            Cornwall, England Houghton, MI  NaN    NaN  NaN   
326   Southampton                          Warwick, England  NaN    NaN  NaN   
...           ...                                       ...  ...    ...  ...   
1308          NaN                                       NaN  NaN    NaN  NaN   
1309          NaN                                       NaN  NaN    NaN  NaN   
1310          NaN                                       NaN  NaN    NaN  NaN   
1311          NaN                                       NaN  NaN    NaN  NaN   
1312          NaN                                       NaN  NaN    NaN  NaN   

         sex  
322     male  
323   female  
324     male  
325     male  
326     male  
...      ...  
1308    male  
1309    male  
1310    male  
1311  female  
1312    male  

[991 rows x 11 columns]

#### Suggest a solution in another way

In [140]:
titanic_df_two_classes = titanic_df.loc[titanic_df.pclass != '1st']
titanic_df_two_classes

row.names pclass  survived                        name   age  \
322         323    2nd         0          Abelson, Mr Samuel  30.0   
323         324    2nd         1  Abelson, Mrs Samuel (Anna)  28.0   
324         325    2nd         0     Andrew, Mr Edgar Samuel  18.0   
325         326    2nd         0            Andrew, Mr Frank   NaN   
326         327    2nd         0        Angle, Mr William A.  34.0   
...         ...    ...       ...                         ...   ...   
1308       1309    3rd         0          Zakarian, Mr Artun   NaN   
1309       1310    3rd         0      Zakarian, Mr Maprieder   NaN   
1310       1311    3rd         0             Zenn, Mr Philip   NaN   
1311       1312    3rd         0               Zievens, Rene   NaN   
1312       1313    3rd         0              Zimmerman, Leo   NaN   

         embarked                                 home.dest room ticket boat  \
322     Cherbourg                       Russia New York, NY  NaN    NaN  NaN   
323     Cherbourg                       Russia New York, NY  NaN    NaN   12   
324   Southampton  Buenos Aires, Argentina / New Jersey, NJ  NaN    NaN  NaN   
325   Southampton            Cornwall, England Houghton, MI  NaN    NaN  NaN   
326   Southampton                          Warwick, England  NaN    NaN  NaN   
...           ...                                       ...  ...    ...  ...   
1308          NaN                                       NaN  NaN    NaN  NaN   
1309          NaN                                       NaN  NaN    NaN  NaN   
1310          NaN                                       NaN  NaN    NaN  NaN   
1311          NaN                                       NaN  NaN    NaN  NaN   
1312          NaN                                       NaN  NaN    NaN  NaN   

         sex  
322     male  
323   female  
324     male  
325     male  
326     male  
...      ...  
1308    male  
1309    male  
1310    male  
1311  female  
1312    male  

[991 rows x 11 columns]

In [118]:
len(titanic_df)

1313

#### 3. Display the oldest age on the ship, display only one row of that age

In [147]:
max_age = titanic_df['age'].max()
max_age

71.0

#### 4. Display the youngest age on the ship, display only one row of that age

In [148]:
min_age = titanic_df['age'].min()
min_age

0.1667

#### 5. Are there more men than women on the ship? Show the solution by a function learned in class
#### Show in 2 different ways

In [153]:
titanic_df_male = titanic_df.loc[titanic_df.sex == 'male']
titanic_df_female = titanic_df.loc[titanic_df.sex == 'female']
len(titanic_df_female) < len(titanic_df_male)

True

In [157]:
titanic_df_male['sex'].count()

print(f"{titanic_df['sex'].unique()[1]} count on board: {titanic_df_male['sex'].count()}")

850

In [158]:
titanic_df_female['sex'].count()

print(f"{titanic_df['sex'].unique()[0]} count on board: {titanic_df_female['sex'].count()}")

463

#### 6. Note that there is a column that shows who survived the disaster, which gender survived more?

In [161]:
titanic_df_male = titanic_df[(titanic_df.sex == 'male') & (titanic_df.survived == 1)]
titanic_df_male['sex'].count()

142

In [162]:
titanic_df_female = titanic_df[(titanic_df.sex == 'female') & (titanic_df.survived == 1)]
titanic_df_female['sex'].count()

307

#### 7. Find the passenger who goes by the name 'Maprieder', did he survive?

In [119]:
titanic_df[titanic_df['name'].str.contains('Maprieder')]                         

row.names pclass  survived                    name  age embarked  \
1309       1310    3rd         0  Zakarian, Mr Maprieder  NaN      NaN   

     home.dest room ticket boat   sex  
1309       NaN  NaN    NaN  NaN  male

#### 8. Is there only one such name ?

In [125]:
titanic_df[titanic_df['name'].str.contains('Maprieder')]['name'].unique()    


array(['Zakarian, Mr Maprieder'], dtype=object)

In [119]:
# With .loc()
country_grp = df[df.loc[:,'Country'] == 'United States of America' ]

In [114]:
country_grp = df.groupby(['Country']).get_group('United States of America')
country_grp

Q120                                         MainBranch  \
ResponseId                                                               
2           I agree                     I am a developer by profession   
3           I agree                     I am a developer by profession   
4           I agree                     I am a developer by profession   
7           I agree                     I am a developer by profession   
8           I agree                     I am a developer by profession   
...             ...                                                ...   
89151       I agree  I used to be a developer by profession, but no...   
89155       I agree                     I am a developer by profession   
89157       I agree                     I am a developer by profession   
89176       I agree                     I am a developer by profession   
89179       I agree                     I am a developer by profession   

                        Age           Employment  \
ResponseId                                         
2           25-34 years old  Employed, full-time   
3           45-54 years old  Employed, full-time   
4           25-34 years old  Employed, full-time   
7           35-44 years old  Employed, full-time   
8           25-34 years old  Employed, full-time   
...                     ...                  ...   
89151       55-64 years old  Employed, full-time   
89155       35-44 years old  Employed, full-time   
89157       25-34 years old  Employed, full-time   
89176       25-34 years old  Employed, full-time   
89179       45-54 years old  Employed, full-time   

                                      RemoteWork  \
ResponseId                                         
2                                         Remote   
3           Hybrid (some remote, some in-person)   
4           Hybrid (some remote, some in-person)   
7                                         Remote   
8                                         Remote   
...                                          ...   
89151                                     Remote   
89155       Hybrid (some remote, some in-person)   
89157                                     Remote   
89176                                     Remote   
89179                                     Remote   

                                             CodingActivities  \
ResponseId                                                      
2           Hobby;Contribute to open-source projects;Boots...   
3           Hobby;Professional development or self-paced l...   
4                                                       Hobby   
7           Hobby;Contribute to open-source projects;Profe...   
8                                                       Hobby   
...                                                       ...   
89151                Hobby;Contribute to open-source projects   
89155                            I don’t code outside of work   
89157       Hobby;Contribute to open-source projects;Profe...   
89176                            I don’t code outside of work   
89179                                                   Hobby   

                                                      EdLevel  \
ResponseId                                                      
2                Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
3                Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
4                Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
7           Some college/university study without earning ...   
8                Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
...                                                       ...   
89151            Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
89155            Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
89157            Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
89176            Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
89179            Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

      