<div style="color:white;display:fill;border-radius:8px;
            background-color:#03112A;font-size:250%; 
            letter-spacing:1.0px;background-image: url(https://i.imgur.com/GVd0La1.png)">
    <p style="padding: 8px;text-align: center;color:white; border-radius: 20px; padding-top: 20px; padding-bottom: 20px;"><b><b><span style='color:#2ae4f5''></span></b> Exercise no. 2 </b></p>
</div>

<b id="up"> </b>  

1. [Pandas](#section1)
2. [loc&iloc](#section2)
3. [conditional selection](#section3)
4. [⭐ Numpy](#section4)
5. [⭐ Random](#section5)
---

<h1 style="background-color: #fff4d9; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction">Quick recap : Functions you have learned so far</h1>

---

>
>* `pd.read_csv` - Read data from a CSV file into a Pandas `DataFrame` object
>
>* `info()` - View basic infomation about rows, columns & data types
>
>* `.columns` - Get the list of column names
>
>* `.shape` - Get the number of rows & columns as a tuple
>
>* `.head(), .tail()` -  View the beginning/end of the file
>
>* `.unique()` - view the unique entries in a series (not a dataframe) object
>
>* `len` - dataframe length (number of rows)
>

---


#### Additional useful functions:


>* `.index.values` - the row indexes of this part of the dataframes
>* `.str.contains` - selects rows and columns that contain a string
>* `.max` - maximum value
>* `.mean` - average value
>* `.count` - the number of rows that contain a value


<div style="color:white;display:fill;border-radius:8px;
            background-color:#03112A;font-size:150%;
            letter-spacing:1.0px;background-image: url(https://i.imgur.com/GVd0La1.png)">
    <p style="padding: 8px;color:white;"><b><b><span style='color:#2ae4f5''> |</span></b> Pandas.</b></p>
</div>

### read file using pandas
### pandas is a fast, powerful, flexible and easy to use open source data analysis in python
### Here we use it to read a csv file

In [1]:
import pandas as pd
print(pd.__version__)

1.4.1


* Here we read from a net repository (github)
* to read from current folder simply write the filename
* guess what is the commmand for the end

In [2]:
#https://raw.githubusercontent.com/Razelbaz1/exercises-package/refs/heads/master/data/titanic_short.csv

In [3]:
import pandas as pd
#encoding='latin1'
url = 'https://github.com/Razelbaz1/exercises-package/blob/master/data/titanic_short.csv' # read from net.
name = 'titanic_short.csv'
path = 'C:\\Users\\razel\\Desktop\\אריאל\\data-analytics\\‏‏My Lectures Sem B 24\\tirgul1\\titanic_short.csv'
data = pd.read_csv(path,encoding='latin1')
data.head(20) # we can set the number of first rows to be displayed.


pclass  survived      age     sex
0     1st         1  29.0000  female
1     1st         0   2.0000  female
2     1st         0  30.0000    male
3     1st         0  25.0000  female
4     1st         1   0.9167    male
5     1st         1  47.0000    male
6     1st         1  63.0000  female
7     1st         0  39.0000    male
8     1st         1  58.0000  female
9     1st         0  71.0000    male
10    1st         0  47.0000    male
11    1st         1  19.0000  female
12    1st         1      NaN  female
13    1st         1      NaN    male
14    1st         0      NaN    male
15    1st         1  50.0000  female
16    1st         0  24.0000    male
17    1st         0  36.0000    male
18    1st         1  37.0000    male
19    1st         1      NaN  female

In [4]:
type(data)

pandas.core.frame.DataFrame

In [5]:
data.tail(10) # set 2 last records

pclass  survived   age     sex
20    1st         1  26.0    male
21    1st         0  25.0    male
22    1st         1   NaN    male
23    1st         1  19.0  female
24    1st         1  28.0    male
25    1st         0   NaN    male
26    1st         1  39.0    male
27    1st         1  30.0  female
28    1st         1  58.0  female
29    1st         0   NaN    male

In [6]:
#### Set specific raws:
data[10:19]

pclass  survived   age     sex
10    1st         0  47.0    male
11    1st         1  19.0  female
12    1st         1   NaN  female
13    1st         1   NaN    male
14    1st         0   NaN    male
15    1st         1  50.0  female
16    1st         0  24.0    male
17    1st         0  36.0    male
18    1st         1  37.0    male

In [7]:
data[data['survived']==1]

pclass  survived      age     sex
0     1st         1  29.0000  female
4     1st         1   0.9167    male
5     1st         1  47.0000    male
6     1st         1  63.0000  female
8     1st         1  58.0000  female
11    1st         1  19.0000  female
12    1st         1      NaN  female
13    1st         1      NaN    male
15    1st         1  50.0000  female
18    1st         1  37.0000    male
19    1st         1      NaN  female
20    1st         1  26.0000    male
22    1st         1      NaN    male
23    1st         1  19.0000  female
24    1st         1  28.0000    male
26    1st         1  39.0000    male
27    1st         1  30.0000  female
28    1st         1  58.0000  female

### Suggest ideas how to display only survivors (denoted in 1)










In [8]:









# data[data['survived'] == 1]
data['survived']== 1

0      True
1     False
2     False
3     False
4      True
5      True
6      True
7     False
8      True
9     False
10    False
11     True
12     True
13     True
14    False
15     True
16    False
17    False
18     True
19     True
20     True
21    False
22     True
23     True
24     True
25    False
26     True
27     True
28     True
29    False
Name: survived, dtype: bool

### Suggest how to display only females gender

In [9]:
data['sex']=='female'

0      True
1      True
2     False
3      True
4     False
5     False
6      True
7     False
8      True
9     False
10    False
11     True
12     True
13    False
14    False
15     True
16    False
17    False
18    False
19     True
20    False
21    False
22    False
23     True
24    False
25    False
26    False
27     True
28     True
29    False
Name: sex, dtype: bool

In [10]:







data[data['sex']=='female']

pclass  survived   age     sex
0     1st         1  29.0  female
1     1st         0   2.0  female
3     1st         0  25.0  female
6     1st         1  63.0  female
8     1st         1  58.0  female
11    1st         1  19.0  female
12    1st         1   NaN  female
15    1st         1  50.0  female
19    1st         1   NaN  female
23    1st         1  19.0  female
27    1st         1  30.0  female
28    1st         1  58.0  female

In [12]:
data1to3 = data[1:4]
data1to3
data1to3[[True,False,True]]

pclass  survived   age     sex
1    1st         0   2.0  female
3    1st         0  25.0  female

### Note that the boolean vectoer must have the same length of data
* For example, this will not work

In [36]:
data1to3[[True,False]]

ValueError: Item wrong length 2 instead of 3.

### Suggest how to display just females survivors

In [13]:









data[(data['survived'] == 1) & (data['sex']=='female')]  

pclass  survived   age     sex
0     1st         1  29.0  female
6     1st         1  63.0  female
8     1st         1  58.0  female
11    1st         1  19.0  female
12    1st         1   NaN  female
15    1st         1  50.0  female
19    1st         1   NaN  female
23    1st         1  19.0  female
27    1st         1  30.0  female
28    1st         1  58.0  female

In [13]:
#### display some of the collumns by a list of collumns
data[[ 'pclass','age']]

pclass      age
0     1st  29.0000
1     1st   2.0000
2     1st  30.0000
3     1st  25.0000
4     1st   0.9167
5     1st  47.0000
6     1st  63.0000
7     1st  39.0000
8     1st  58.0000
9     1st  71.0000
10    1st  47.0000
11    1st  19.0000
12    1st      NaN
13    1st      NaN
14    1st      NaN
15    1st  50.0000
16    1st  24.0000
17    1st  36.0000
18    1st  37.0000
19    1st      NaN
20    1st  26.0000
21    1st  25.0000
22    1st      NaN
23    1st  19.0000
24    1st  28.0000
25    1st      NaN
26    1st  39.0000
27    1st  30.0000
28    1st  58.0000
29    1st      NaN

In [39]:
#### Number of rows and collumns by shape attribute:
data.shape

(30, 4)

In [40]:
#### Get more information such as the column names by info() method
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pclass    30 non-null     object 
 1   survived  30 non-null     int64  
 2   age       23 non-null     float64
 3   sex       30 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ KB


<div style="color:white;border-radius:10px; padding-top: 2px; padding-bottom: 0px;
            background-color:#03112A;font-size:150%;
            letter-spacing:1.0px;color:white; text-align: center;"><b><b><span style='color:#2ae4f5''> </span></b> loc & iloc</b></p>
</div>



### Here is a fictitious data for practice

In [14]:
import pandas as pd

# Create some variables
trials = range(1, 21)
n_rows = len(trials)
subj_id = [1]*n_rows
group = ['Control']*n_rows
condition = ['Affect']*int((n_rows/2)) + ['Neutral']*int((n_rows/2))

# Create a dictionary
data = {'Condition':condition, 'Subject_ID':subj_id, 
        'Trial':trials, 'Group':group}

# Create the dataframe
df = pd.DataFrame(data)
df.head(10)

Condition  Subject_ID  Trial    Group
0    Affect           1      1  Control
1    Affect           1      2  Control
2    Affect           1      3  Control
3    Affect           1      4  Control
4    Affect           1      5  Control
5    Affect           1      6  Control
6    Affect           1      7  Control
7    Affect           1      8  Control
8    Affect           1      9  Control
9    Affect           1     10  Control

#### 1. Select row five to 10 __without__ using loc / iloc


In [37]:
# Select row five to 10 
df[4:10:1] 

Condition  Subject_ID  Trial    Group
4    Affect           1      5  Control
5    Affect           1      6  Control
6    Affect           1      7  Control
7    Affect           1      8  Control
8    Affect           1      9  Control
9    Affect           1     10  Control

#### 2. Select row five to 10 by using loc 

In [23]:
df.loc[5:10,:]  # df.loc[rowNum:rowNum , colNum:colNum]

Condition  Subject_ID  Trial    Group
5     Affect           1      6  Control
6     Affect           1      7  Control
7     Affect           1      8  Control
8     Affect           1      9  Control
9     Affect           1     10  Control
10   Neutral           1     11  Control

#### 3. Show only the value from row number 0 under the "Conditions" column

In [18]:
df.loc[0, 'Condition']

'Affect'

#### 4.1  print only the "Conditions" column , show all rows

In [23]:
# Printing out one column
df.loc[:, ['Condition']]

Condition
0     Affect
1     Affect
2     Affect
3     Affect
4     Affect
5     Affect
6     Affect
7     Affect
8     Affect
9     Affect
10   Neutral
11   Neutral
12   Neutral
13   Neutral
14   Neutral
15   Neutral
16   Neutral
17   Neutral
18   Neutral
19   Neutral

#### 4.2  print only the "Conditions" and 'Group' column , show all rows

In [28]:
# Printing out two columns
df.loc[:, ['Condition', 'Group']]

Condition    Group
0     Affect  Control
1     Affect  Control
2     Affect  Control
3     Affect  Control
4     Affect  Control
5     Affect  Control
6     Affect  Control
7     Affect  Control
8     Affect  Control
9     Affect  Control
10   Neutral  Control
11   Neutral  Control
12   Neutral  Control
13   Neutral  Control
14   Neutral  Control
15   Neutral  Control
16   Neutral  Control
17   Neutral  Control
18   Neutral  Control
19   Neutral  Control

#### 5. Combine your answer from question 2 and question 4.2

In [8]:
# Printing out from second column
df.loc[4:9, ['Condition', 'Group']]

Condition    Group
4    Affect  Control
5    Affect  Control
6    Affect  Control
7    Affect  Control
8    Affect  Control
9    Affect  Control

#### 6. According to the slice you made in question 2: display the columns starting from the  'Subject_ID' column and forward and display again starting from 'Trial' column and forward

In [24]:
# From column 'Subject_ID' and forward
df.loc[4:9, 'Subject_ID':]

# From column 'Trial' and forward
df.loc[4:9, 'Trial':]

Trial    Group
4      5  Control
5      6  Control
6      7  Control
7      8  Control
8      9  Control
9     10  Control

#### 7.1 Display the same dataframe as you did in question #1 by using __iloc__

In [10]:
# Printing out fifth to the twentieth row and all columns
# Note the difference!
df.iloc[4:10,:]

Condition  Subject_ID  Trial    Group
4    Affect           1      5  Control
5    Affect           1      6  Control
6    Affect           1      7  Control
7    Affect           1      8  Control
8    Affect           1      9  Control
9    Affect           1     10  Control

#### 7.2 Now show only the first column

In [11]:
df.iloc[4:10, 0]

4    Affect
5    Affect
6    Affect
7    Affect
8    Affect
9    Affect
Name: Condition, dtype: object

#### Display the first and last column by using __iloc__ , show all rows

In [47]:
df.iloc[4:10, [0, 3]]

Condition    Group
4    Affect  Control
5    Affect  Control
6    Affect  Control
7    Affect  Control
8    Affect  Control
9    Affect  Control

#### Show all columns except the first column

In [13]:
df.iloc[4:10, 1:]

Subject_ID  Trial    Group
4           1      5  Control
5           1      6  Control
6           1      7  Control
7           1      8  Control
8           1      9  Control
9           1     10  Control

#### According to the following line of code - what do you think will be displayed in the output?

### [▲](#up)
---

<div style="color:white;border-radius:10px; padding-top: 2px; padding-bottom: 0px;
            background-color:#03112A;font-size:150%;
            letter-spacing:1.0px;color:white; text-align: center;"><b><b><span style='color:#2ae4f5''> </span></b> conditional selection </b></p>
</div>




#### Summary of the functions in unit 2:


>* `.index.values` - the row indexes of this part of the dataframes
>* `.str.contains` - selects rows and columns that contain a string
>* `.max` - maximum value
>* `.mean` - average value
>* `.count` - the number of rows that contain a value
>* `len()` - dataframe length

In [25]:
url = 'https://raw.githubusercontent.com/Razelbaz1/exercises-package/master/data/titanic.csv'
titanic_df = pd.read_csv(url, encoding= 'latin1')

In [26]:
titanic_df.columns

Index(['row.names', 'pclass', 'survived', 'name', 'age', 'embarked',
       'home.dest', 'room', 'ticket', 'boat', 'sex'],
      dtype='object')

#### 1. Display a table so that you see all the passengers who belong to the third class
##### For your convenience, the list of columns is given

In [27]:
titanic_df[titanic_df.loc[:,'pclass'] == '3rd' ].head()

row.names pclass  survived                          name   age  \
602        603    3rd         0            Abbing, Mr Anthony  42.0   
603        604    3rd         0  Abbott, Master Eugene Joseph  13.0   
604        605    3rd         0    Abbott, Mr Rossmore Edward  16.0   
605        606    3rd         1    Abbott, Mrs Stanton (Rosa)  35.0   
606        607    3rd         1     Abelseth, Miss Anna Karen  16.0   

        embarked               home.dest room ticket  boat     sex  
602  Southampton                     NaN  NaN    NaN   NaN    male  
603  Southampton     East Providence, RI  NaN    NaN   NaN    male  
604  Southampton     East Providence, RI  NaN    NaN  -190    male  
605  Southampton     East Providence, RI  NaN    NaN     A  female  
606  Southampton  Norway Los Angeles, CA  NaN    NaN    16  female

#### 2. Display a table so that you see all the passengers belonging to the third <ins>**or**</ins> second class

In [15]:
titanic_df_two_classes = titanic_df[(titanic_df.pclass == '3rd') | (titanic_df.pclass == '2nd')]
titanic_df_two_classes

row.names pclass  survived                        name   age  \
322         323    2nd         0          Abelson, Mr Samuel  30.0   
323         324    2nd         1  Abelson, Mrs Samuel (Anna)  28.0   
324         325    2nd         0     Andrew, Mr Edgar Samuel  18.0   
325         326    2nd         0            Andrew, Mr Frank   NaN   
326         327    2nd         0        Angle, Mr William A.  34.0   
...         ...    ...       ...                         ...   ...   
1308       1309    3rd         0          Zakarian, Mr Artun   NaN   
1309       1310    3rd         0      Zakarian, Mr Maprieder   NaN   
1310       1311    3rd         0             Zenn, Mr Philip   NaN   
1311       1312    3rd         0               Zievens, Rene   NaN   
1312       1313    3rd         0              Zimmerman, Leo   NaN   

         embarked                                 home.dest room ticket boat  \
322     Cherbourg                       Russia New York, NY  NaN    NaN  NaN   
323     Cherbourg                       Russia New York, NY  NaN    NaN   12   
324   Southampton  Buenos Aires, Argentina / New Jersey, NJ  NaN    NaN  NaN   
325   Southampton            Cornwall, England Houghton, MI  NaN    NaN  NaN   
326   Southampton                          Warwick, England  NaN    NaN  NaN   
...           ...                                       ...  ...    ...  ...   
1308          NaN                                       NaN  NaN    NaN  NaN   
1309          NaN                                       NaN  NaN    NaN  NaN   
1310          NaN                                       NaN  NaN    NaN  NaN   
1311          NaN                                       NaN  NaN    NaN  NaN   
1312          NaN                                       NaN  NaN    NaN  NaN   

         sex  
322     male  
323   female  
324     male  
325     male  
326     male  
...      ...  
1308    male  
1309    male  
1310    male  
1311  female  
1312    male  

[991 rows x 11 columns]

#### Suggest a solution in another way

In [16]:
titanic_df_two_classes = titanic_df.loc[titanic_df.pclass != '1st']
titanic_df_two_classes

row.names pclass  survived                        name   age  \
322         323    2nd         0          Abelson, Mr Samuel  30.0   
323         324    2nd         1  Abelson, Mrs Samuel (Anna)  28.0   
324         325    2nd         0     Andrew, Mr Edgar Samuel  18.0   
325         326    2nd         0            Andrew, Mr Frank   NaN   
326         327    2nd         0        Angle, Mr William A.  34.0   
...         ...    ...       ...                         ...   ...   
1308       1309    3rd         0          Zakarian, Mr Artun   NaN   
1309       1310    3rd         0      Zakarian, Mr Maprieder   NaN   
1310       1311    3rd         0             Zenn, Mr Philip   NaN   
1311       1312    3rd         0               Zievens, Rene   NaN   
1312       1313    3rd         0              Zimmerman, Leo   NaN   

         embarked                                 home.dest room ticket boat  \
322     Cherbourg                       Russia New York, NY  NaN    NaN  NaN   
323     Cherbourg                       Russia New York, NY  NaN    NaN   12   
324   Southampton  Buenos Aires, Argentina / New Jersey, NJ  NaN    NaN  NaN   
325   Southampton            Cornwall, England Houghton, MI  NaN    NaN  NaN   
326   Southampton                          Warwick, England  NaN    NaN  NaN   
...           ...                                       ...  ...    ...  ...   
1308          NaN                                       NaN  NaN    NaN  NaN   
1309          NaN                                       NaN  NaN    NaN  NaN   
1310          NaN                                       NaN  NaN    NaN  NaN   
1311          NaN                                       NaN  NaN    NaN  NaN   
1312          NaN                                       NaN  NaN    NaN  NaN   

         sex  
322     male  
323   female  
324     male  
325     male  
326     male  
...      ...  
1308    male  
1309    male  
1310    male  
1311  female  
1312    male  

[991 rows x 11 columns]

In [56]:
len(titanic_df)

1313

#### 3. Display the oldest age on the ship, display only one row of that age

In [18]:
max_age = titanic_df['age'].max()
max_age

71.0

#### 4. Display the youngest age on the ship, display only one row of that age

In [19]:
min_age = titanic_df['age'].min()
min_age

0.1667

#### 5. Are there more men than women on the ship? Show the solution by a function learned in class
#### Show in 2 different ways

In [20]:
titanic_df_male = titanic_df.loc[titanic_df.sex == 'male']
titanic_df_female = titanic_df.loc[titanic_df.sex == 'female']
len(titanic_df_female) < len(titanic_df_male)

True

In [21]:
titanic_df_male['sex'].count()

print(f"{titanic_df['sex'].unique()[1]} count on board: {titanic_df_male['sex'].count()}")

male count on board: 850


In [22]:
titanic_df_female['sex'].count()

print(f"{titanic_df['sex'].unique()[0]} count on board: {titanic_df_female['sex'].count()}")

female count on board: 463


#### 6. Note that there is a column that shows who survived the disaster, which gender survived more?

In [23]:
titanic_df_male = titanic_df[(titanic_df.sex == 'male') & (titanic_df.survived == 1)]
titanic_df_male['sex'].count()

142

In [24]:
titanic_df_female = titanic_df[(titanic_df.sex == 'female') & (titanic_df.survived == 1)]
titanic_df_female['sex'].count()

307

#### 7. Find the passenger who goes by the name 'Maprieder', did he survive?

In [25]:
titanic_df[titanic_df['name'].str.contains('Maprieder')]                         

row.names pclass  survived                    name  age embarked  \
1309       1310    3rd         0  Zakarian, Mr Maprieder  NaN      NaN   

     home.dest room ticket boat   sex  
1309       NaN  NaN    NaN  NaN  male

#### 8. Is there only one such name ?

In [26]:
titanic_df[titanic_df['name'].str.contains('Maprieder')]['name'].unique()    


array(['Zakarian, Mr Maprieder'], dtype=object)

<div style="color:white;border-radius:10px; padding-top: 2px; padding-bottom: 0px;
            background-color:#03112A;font-size:150%;
            letter-spacing:1.0px;color:white; text-align: center;"><b><b><span style='color:#2ae4f5''> </span></b>⭐ NumPy </b></p>
</div>



<a id='section2'></a>

<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/Title_numpy.png?raw=true" width="20%" height="20%" alt="Centered Image" /> <div  </h1>

<h1 style="background-color: #FFFFFF; color: #0046d6; border-radius: 10px; text-align: center; padding-top: 10px; padding-bottom: 10px; font-family: 'Arial'" id="introduction"><img src="https://github.com/Razelbaz1/exercises-package/blob/master/pics/Uses-of-NumPy-1.png?raw=true" width="40%" height="40%" alt="Centered Image" /> <div  </h1>

---

### Numpy in terms of complexity



In [48]:
import numpy as np
import pandas as pd 

In [49]:
%%time 
my_list = list(range(10000000))
mult_by_3 = [3 * num for num in my_list]

CPU times: total: 641 ms
Wall time: 1.04 s


In [51]:
%%time 
my_array = np.arange(10000000)
mult_by_3 = 3 * my_array


CPU times: total: 15.6 ms
Wall time: 38.2 ms


In [52]:
1.06 / 33.6 * 0.001 

3.154761904761905e-05

### 3x faster using numpy
---

### <b >Vectors with </b> <b style='color:#32B1FF'>Numpy. </b> 

In [30]:
arr = np.array([1, 2, 3, 4, 5])
# . product
print(arr*arr)

[ 1  4  9 16 25]


#### vector multiplication

In [31]:

arr.dot(arr)
# or by
arr@arr


55

* create ones matrix of specific size:

In [32]:

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

* self excercise: Suggest how to create zeros matrix of specific size:

In [33]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

* Create any constant array

In [34]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [35]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


* self excercise: suggest how to create a 3X3 matrix where digonal has value of 8

In [36]:
8*np.eye(3)

array([[8., 0., 0.],
       [0., 8., 0.],
       [0., 0., 8.]])

In [37]:
e = np.random.random((2,4))
print(e)

[[0.36667754 0.89271365 0.12418737 0.52210356]
 [0.15130171 0.20509965 0.74131903 0.39811305]]


#### self learning:
1. Read Lec3
2. Read the tutorials in links
3. Write a NumPy program to test whether none of the elements of a given array is zero (create a sample array).

In [38]:



import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


<div style="color:white;border-radius:10px; padding-top: 2px; padding-bottom: 0px;
            background-color:#03112A;font-size:150%;
            letter-spacing:1.0px;color:white; text-align: center;"><b><b><span style='color:#2ae4f5''> </span></b>⭐ Random </b></p>
</div>



In [1]:
import random # import library

In [19]:
# Method 1- using random method
num = random.random()
print(num)
# Result will always between (0,1)

0.16749674115113278


In [20]:
# Method 2- using randint method ---> Rand - int ---
num = random.randint(10, 20)
print(num)

18


In [21]:
#Try to compute 
num = random.randint(10.5, 10.6) 
# Why is that ?

ValueError: non-integer arg 1 for randrange()

In [22]:
# Method 3- using randrange method

num = random.randrange(100,200,2) # (Start,Stop,Step)
print(num)

152


In [23]:
# Method 4- using uniform method

num = random.uniform(50,70) # (a,b)  
print(num)

# The uniform() method returns a random floating number between the two specified numbers
# (both included).

65.37878489014041


In [24]:
# Method 5- using sample method

numList = random.sample(range(150,250), 15)
print(numList)



[178, 162, 212, 185, 152, 219, 223, 196, 163, 239, 204, 203, 191, 232, 210]


In [25]:
# Method 6- using shuffle and choice method

numList = [1,2,3,4,5]
random.shuffle(numList)
print(numList)
print(random.choice(numList))

[2, 5, 3, 4, 1]
4


In [26]:
# Method 7 - using random.choices is the same as #6 , try yourself !
# random.choices()

In [27]:
# Nice greeting

greetings = ['Hello', 'Hi', 'Hey', 'Howdy', 'Hola']
value = random.choice(greetings)
my_name = 'Your_Name'
print(value + ', ' + my_name)

Hi, Your_Name


### Exercise
#### Write a coin flip code, with 10 samples

In [28]:
coin = ['Tail', 'Head']
value = random.choices(coin, k =10)
print(value)

['Tail', 'Tail', 'Tail', 'Tail', 'Head', 'Tail', 'Tail', 'Tail', 'Tail', 'Tail']


#### Write code to flip an unfair coin so that the chance of getting a head is 90 percent

In [29]:
coin = ['Tail', 'Head']
value = random.choices(coin, weights= [1,9], k = 10)
print(value)

['Head', 'Head', 'Head', 'Head', 'Head', 'Head', 'Head', 'Head', 'Head', 'Head']
